import React from 'react';
import Header from '../components/Header';
import Footer from '../components/Footer';
import { SafeEmail } from '../components/SafeContact';

const Section = ({ title, children }) => (
  <div className="mb-10">
    <h2 className="font-heading text-2xl font-bold mb-3" style={{ color: 'var(--text-primary)' }}>{title}</h2>
    <div className="w-8 h-0.5 rounded-full mb-4" style={{ background: 'var(--primary)' }} />
    <div className="font-body leading-relaxed space-y-3" style={{ color: 'var(--text-secondary)' }}>{children}</div>
  </div>
);

const TermsAndConditions = () => {
  const updated = 'June 1, 2026';
  return (
    <div className="min-h-screen" style={{ background: 'var(--background)' }}>
      <Header />
      <div className="py-14 px-4 text-center" style={{ background: 'linear-gradient(135deg, #1F1A17 0%, #3A2E2A 100%)' }}>
        <h1 className="font-heading text-4xl md:text-5xl font-bold text-white mb-3">Terms & Conditions</h1>
        <p className="font-body text-sm" style={{ color: '#A09890' }}>Last updated: {updated}</p>
      </div>

      <div className="max-w-4xl mx-auto px-4 py-14">
        <div className="bg-white rounded-2xl p-8 md:p-12" style={{ border: '1px solid var(--border)', boxShadow: '0 4px 24px rgba(0,0,0,0.06)' }}>
          <p className="font-body mb-10 p-4 rounded-xl text-sm" style={{ background: 'rgba(200,75,49,0.06)', color: 'var(--text-secondary)', borderLeft: '4px solid var(--primary)' }}>
            Welcome to Satnami Matrimony (also known as Satnami Shaadi). This website is operated by <strong>Roonal Khandelwal</strong>, located at <span data-nosnippet="">10/1143 Shivanand Nagar Sec-1, Khamtarai, Raipur, Chhattisgarh – 492008</span>. By accessing or using our website (satnamishaadiii.com) and services, you agree to be bound by these Terms & Conditions.
          </p>

          <Section title="1. Agreement & Acceptance">
            <p>
              This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under as applicable. This electronic record is generated by a computer system and does not require any physical or digital signatures.
            </p>
            <p>
              By registering on our platform, you confirm that you have read, understood, and agreed to these Terms & Conditions. If you do not agree to these terms, please do not register or use our matchmaking services.
            </p>
          </Section>

          <Section title="2. Eligibility Criteria">
            <p>To register as a member of Satnami Matrimony or use this website, you must meet the following criteria:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>You must be of legal marriageable age in India (currently 18 years or above for females and 21 years or above for males) or the legal marriageable age of your country of residence.</li>
              <li>You must be legally competent to contract under applicable laws.</li>
              <li>You must be single, legally divorced, widowed, or have your previous marriage legally annulled.</li>
              <li>You must belong to or seek a partner within the Satnami community, as this is a community-centric matchmaking platform.</li>
            </ul>
          </Section>

          <Section title="3. Account Security & Verification">
            <p>
              When you create an account, you are responsible for maintaining the confidentiality of your login credentials (username and password) and for restricting access to your device. You agree to accept responsibility for all activities that occur under your account.
            </p>
            <p>
              <strong>Profile Verification:</strong> To maintain safety and trust on our platform, we encourage and reserve the right to require members to undergo identity verification. This may include uploading government-issued IDs, email verification, or selfie verification. While we perform basic checks, we do not guarantee the background, character, or credentials of any member. You are strongly advised to conduct independent checks before entering into any matrimonial commitments.
            </p>
          </Section>

          <Section title="4. Code of Conduct & Prohibited Activities">
            <p>You agree to use our matchmaking platform in a polite, respectful, and lawful manner. The following actions are strictly prohibited and will lead to immediate account suspension or termination without refund:</p>
            <ul className="list-disc pl-5 space-y-1">
              <li>Creating multiple accounts or impersonating another person.</li>
              <li>Uploading fake, misleading, obscene, pornographic, copyrighted, or offensive profile information or photos.</li>
              <li>Harassing, abusing, threatening, or stalking other members.</li>
              <li>Using our platform for commercial purposes, advertising, or selling any products or services.</li>
              <li>Sending unsolicited mass messages, spam, chain letters, or asking other members for money, financial assistance, or loans.</li>
              <li>Scraping, harvesting, or extracting member data using bots, automated scripts, or software tools.</li>
            </ul>
          </Section>

          <Section title="5. Membership Fees & Billing">
            <p>
              We offer both free (basic) and premium (paid) subscriptions. The features and pricing of each plan are detailed on our Premium page.
            </p>
            <p>
              Payments are processed securely via the Dodo Payments gateway. We do not store card details, net banking credentials, or UPI PINs on our servers. All premium memberships are one-time payments for a fixed duration. They do not auto-renew; you must manually renew your subscription when it expires.
            </p>
            <p>
              All purchases are subject to our <strong>Return & Refund Policy</strong>.
            </p>
          </Section>

          <Section title="6. User Content & Intellectual Property">
            <p>
              You own the content and information you submit or post on our website (such as profile details and photos). By posting content, you grant Satnami Matrimony a non-exclusive, royalty-free, worldwide license to host, display, process, and distribute your content for the sole purpose of providing matchmaking services to you.
            </p>
            <p>
              The layout, design, graphics, logo, code, and trademarks of Satnami Matrimony are owned by Roonal Khandelwal and protected by intellectual property laws. You may not copy, reproduce, modify, or distribute any part of our platform without prior written permission.
            </p>
          </Section>

          <Section title="7. Term & Termination">
            <p>
              These Terms & Conditions remain in effect as long as you are a registered user of our website. You may terminate your membership at any time by requesting account deletion via your settings or by writing to us at <SafeEmail linkClassName="underline" linkStyle={{ color: 'var(--primary)' }} />.
            </p>
            <p>
              We reserve the right to suspend or terminate your profile immediately, without notice or explanation, if we believe you have breached these Terms & Conditions or if we receive complaints from other members regarding your conduct.
            </p>
          </Section>

          <Section title="8. Disclaimers & Matchmaking Intermediary">
            <p>
              <strong>As-Is Basis:</strong> Our website and matchmaking services are provided on an "as-is" and "as-available" basis. We make no warranties of any kind, whether express or implied, regarding the accuracy, completeness, or reliability of any profile data or the compatibility of potential matches.
            </p>
            <p>
              <strong>Intermediary Status:</strong> Under Section 79 of the Information Technology Act, 2000, Satnami Matrimony acts solely as an online intermediary connecting prospective brides and grooms. We do not participate in negotiations, family background checks, or final marriage decisions. You assume full responsibility for any risks associated with meeting, communicating with, or marrying other members.
            </p>
          </Section>

          <Section title="9. Limitation of Liability & Indemnity">
            <p>
              To the maximum extent permitted by law, Roonal Khandelwal, Satnami Matrimony, or our team shall not be liable for any direct, indirect, incidental, special, or consequential damages resulting from your use of our services, including emotional distress, financial loss, or disputes between members.
            </p>
            <p>
              You agree to indemnify and hold harmless Roonal Khandelwal, Satnami Matrimony, and our representatives from and against any claims, losses, liabilities, or legal expenses arising out of your breach of these Terms & Conditions, your posted content, or your interactions with other members.
            </p>
          </Section>

          <Section title="10. Governing Law & Jurisdiction">
            <p>
              These Terms & Conditions shall be governed by and construed in accordance with the laws of India. Any disputes arising in connection with these terms, our services, or transactions on our platform shall be subject to the exclusive jurisdiction of the courts located in <strong>Raipur, Chhattisgarh, India</strong>.
            </p>
          </Section>

          <Section title="11. Grievance Redressal & Contact">
            <p>If you have any questions, feedback, or complaints regarding these Terms & Conditions, or if you wish to report misuse of the platform, contact our Grievance Officer:</p>
            <div className="p-4 rounded-xl mt-4" style={{ background: 'var(--surface-secondary)' }} data-nosnippet="">
              <p><strong>Grievance Officer: Roonal Khandelwal</strong></p>
              <p>Address: 10/1143 Shivanand Nagar Sec-1, Khamtarai, Raipur, Chhattisgarh – 492008</p>
              <p>Email: <SafeEmail linkStyle={{ color: 'var(--primary)' }} /></p>
            </div>
          </Section>
        </div>
      </div>
      <Footer />
    </div>
  );
};

export default TermsAndConditions;
